pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Build Downstream job uat'){
            steps {
                build 'uat'
            }
        }
        stage('Build Downstream job prod'){
            steps {
                build 'prod'
            }
        }
        stage('Email trigger') {
            steps {
                emailext body: 'pipeline jobs dev,uat and prod were success message', subject: 'Build status.', to: 'cloudops990@gmail.com'
            }
        }
    }
}
